In [1]:
import pandas as pd
import numpy as np

In [2]:
# Study data files
countryhappiness_path = "country_trial.csv"

# Read the mouse data and the study results
country_happiness = pd.read_csv(countryhappiness_path)

country_happiness

,Overall rank,Country Code,Country,Region,Languages,Religion,Population,Area (km2),2015 Happiness Score,2016 Happiness Score,...,Drugs Usage (per cap),Antidepressants (per cap),Congestion (Per capita),Power Distance,Individualism,Masculinity,Uncertainity Avoidance,Long Term Orientation,Net Migration,Mortality
0,153.0,AFG,Afghanistan,Southern Asia,Asia (other),Muslim,34414000.0,652860.0,3.58,3.36,...,2.54,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.3,6.93
1,137.0,AGO,Angola,Sub-Saharan Africa,Portuguese,Christian,27884000.0,1246700.0,4.03,3.87,...,0.51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.4,9.05
2,95.0,ALB,Albania,Eastern Europe,Europe (other),Muslim,2891000.0,27400.0,4.96,4.66,...,0.51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-9.4,7.37
3,20.0,ARE,United Arab Emirates,Middle East and Northern Africa,Arabic,Muslim,9263000.0,71020.0,6.90,6.57,...,2.99,NaN,170.89,80.0,38.0,52.0,68.0,0.0,6.1,1.38
4,30.0,ARG,Argentina,Latin America and Caribbean,Spanish,Christian,43075000.0,2736690.0,6.57,6.65,...,0.99,NaN,172.79,49.0,46.0,56.0,86.0,0.0,0.1,7.64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,69.0,XKX,Kosovo,Eastern Europe,Europe (other),Muslim,NaN,NaN,5.59,5.40,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.00
156,136.0,YEM,Yemen,Middle East and Northern Africa,Arabic,Muslim,26498000.0,527970.0,4.08,3.72,...,1.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.6,5.97
157,113.0,ZAF,South Africa,Sub-Saharan Africa,English,Christian,55386000.0,1213090.0,4.64,4.46,...,0.96,NaN,191.72,49.0,65.0,63.0,49.0,0.0,3.5,9.77
158,85.0,ZMB,Zambia,Sub-Saharan Africa,English,Christian,15879000.0,743390.0,5.13,4.80,...,0.51,NaN,NaN,64.0,27.0,41.0,52.0,25.0,-0.7,7.17
159,115.0,ZWE,Zimbabwe,Sub-Saharan Africa,English,Christian,13815000.0,386850.0,4.61,4.19,...,0.77,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-9.4,8.67

In [3]:
#Creating data frame with happiness scores
Happiness_fouryears = country_happiness.loc[:,['Country', '2015 Happiness Score','2016 Happiness Score',
                                               '2017 Happiness Score','2018 Happiness Score','2019 Happiness Score']]

In [4]:
Happiness_fouryears

,Country,2015 Happiness Score,2016 Happiness Score,2017 Happiness Score,2018 Happiness Score,2019 Happiness Score
0,Afghanistan,3.58,3.36,3.79,3.63,3.20
1,Angola,4.03,3.87,3.80,3.80,NaN
2,Albania,4.96,4.66,4.64,4.59,4.72
3,United Arab Emirates,6.90,6.57,6.65,6.77,6.83
4,Argentina,6.57,6.65,6.60,6.39,6.09
...,...,...,...,...,...,...
155,Kosovo,5.59,5.40,5.28,5.66,6.10
156,Yemen,4.08,3.72,3.59,3.36,3.38
157,South Africa,4.64,4.46,4.83,4.72,4.72
158,Zambia,5.13,4.80,4.51,4.38,4.11
159,Zimbabwe,4.61,4.19,3.88,3.69,3.66

In [5]:
#check and count null values
Happiness_fouryears['2015 Happiness Score'].isnull().sum()
Happiness_fouryears['2017 Happiness Score'].isnull().sum()
Happiness_fouryears['2018 Happiness Score'].isnull().sum()
Happiness_fouryears['2019 Happiness Score'].isnull().sum()

# We could drop these countries without happiness scores in certain years but there's not many empty values, 
#let's fill the data instead through a logical way

Incomplete_Countries = Happiness_fouryears[Happiness_fouryears.isna().any(axis=1)]
Incomplete_Countries

,Country,2015 Happiness Score,2016 Happiness Score,2017 Happiness Score,2018 Happiness Score,2019 Happiness Score
1,Angola,4.03,3.87,3.80,3.80,NaN
18,Belize,NaN,5.96,5.96,5.96,NaN
23,Central African Republic,3.68,NaN,2.69,3.08,3.08
33,Comoros,3.96,3.96,NaN,NaN,3.97
38,Djibouti,4.37,NaN,NaN,NaN,NaN
54,Gambia,NaN,NaN,NaN,NaN,4.52
79,Laos,4.88,4.88,NaN,4.62,4.80
84,Lesotho,4.90,NaN,3.81,3.81,3.80
98,Mozambique,4.97,NaN,4.55,4.42,4.47
103,Namibia,NaN,4.57,4.57,4.44,4.64
111,Oman,6.85,NaN,NaN,NaN,NaN
117,Puerto Rico,NaN,7.04,NaN,NaN,NaN
125,Sudan,4.55,4.14,4.14,4.14,NaN
130,Somalia,NaN,5.44,5.15,4.98,4.67
132,South Sudan,NaN,3.83,3.59,3.25,2.85
133,Suriname,6.27,6.27,NaN,NaN,NaN
137,Swaziland,4.87,NaN,NaN,NaN,4.21

In [6]:
# To decide the most logical value we'll run thrugh each country

#Countries with no value changes
Happiness_fouryears.at[Happiness_fouryears["Country"]=="Angola",'2019 Happiness Score']=3.8
Happiness_fouryears.at[Happiness_fouryears["Country"]=="Belize",{'2015 Happiness Score','2019 Happiness Score'}]=5.96
Happiness_fouryears.at[Happiness_fouryears["Country"]=="Comoros",{'2017 Happiness Score','2018 Happiness Score'}]=3.96
Happiness_fouryears.at[Happiness_fouryears["Country"]=="Djibouti",{'2016 Happiness Score','2017 Happiness Score'}]=4.37
Happiness_fouryears.at[Happiness_fouryears["Country"]=="Djibouti",{'2018 Happiness Score','2019 Happiness Score'}]=4.37
Happiness_fouryears.at[Happiness_fouryears["Country"]=="Gambia",{'2015 Happiness Score','2016 Happiness Score'}]=4.52
Happiness_fouryears.at[Happiness_fouryears["Country"]=="Gambia",{'2017 Happiness Score','2018 Happiness Score'}]=4.52
Happiness_fouryears.at[Happiness_fouryears["Country"]=="Oman",{'2016 Happiness Score','2017 Happiness Score'}]=6.85
Happiness_fouryears.at[Happiness_fouryears["Country"]=="Oman",{'2018 Happiness Score','2019 Happiness Score'}]=6.85
Happiness_fouryears.at[Happiness_fouryears["Country"]=="Puerto Rico",{'2015 Happiness Score','2017 Happiness Score'}]=7.04
Happiness_fouryears.at[Happiness_fouryears["Country"]=="Puerto Rico",{'2018 Happiness Score','2019 Happiness Score'}]=7.04
Happiness_fouryears.at[Happiness_fouryears["Country"]=="Suriname",{'2017 Happiness Score','2018 Happiness Score'}]=6.27
Happiness_fouryears.at[Happiness_fouryears["Country"]=="Suriname",'2019 Happiness Score']=6.27
Happiness_fouryears.at[Happiness_fouryears["Country"]=="Namibia",'2015 Happiness Score']=4.57
Happiness_fouryears.at[Happiness_fouryears["Country"]=="Sudan",'2019 Happiness Score']=4.14

# Countries with value changes, do a linear transition
Happiness_fouryears.at[Happiness_fouryears["Country"]=="Central African Republic",'2016 Happiness Score']=(3.86+2.69)/2
Happiness_fouryears.at[Happiness_fouryears["Country"]=="Laos",'2017 Happiness Score']=(4.88+4.62)/2
Happiness_fouryears.at[Happiness_fouryears["Country"]=="Lesotho",'2016 Happiness Score']=(4.90+3.81)/2
Happiness_fouryears.at[Happiness_fouryears["Country"]=="Mozambique",'2016 Happiness Score']=(4.97+4.55)/2
Happiness_fouryears.at[Happiness_fouryears["Country"]=="Somalia",'2015 Happiness Score']=(5.44+(5.44-5.15))
Happiness_fouryears.at[Happiness_fouryears["Country"]=="South Sudan",'2015 Happiness Score']=(3.83+(3.88-3.59))
Happiness_fouryears.at[Happiness_fouryears["Country"]=="Swaziland",'2016 Happiness Score']=4.87-(4.87-4.21)/3
Happiness_fouryears.at[Happiness_fouryears["Country"]=="Swaziland",'2017 Happiness Score']=4.65-(4.87-4.21)/3
Happiness_fouryears.at[Happiness_fouryears["Country"]=="Swaziland",'2018 Happiness Score']=4.43-(4.87-4.21)/3


#checker
Incomplete_Countries = Happiness_fouryears[Happiness_fouryears.isna().any(axis=1)]
Incomplete_Countries

Empty DataFrame
Columns: [Country, 2015 Happiness Score, 2016 Happiness Score, 2017 Happiness Score, 2018 Happiness Score, 2019 Happiness Score]
Index: []

In [7]:
Happiness_fouryears

,Country,2015 Happiness Score,2016 Happiness Score,2017 Happiness Score,2018 Happiness Score,2019 Happiness Score
0,Afghanistan,3.58,3.36,3.79,3.63,3.20
1,Angola,4.03,3.87,3.80,3.80,3.80
2,Albania,4.96,4.66,4.64,4.59,4.72
3,United Arab Emirates,6.90,6.57,6.65,6.77,6.83
4,Argentina,6.57,6.65,6.60,6.39,6.09
...,...,...,...,...,...,...
155,Kosovo,5.59,5.40,5.28,5.66,6.10
156,Yemen,4.08,3.72,3.59,3.36,3.38
157,South Africa,4.64,4.46,4.83,4.72,4.72
158,Zambia,5.13,4.80,4.51,4.38,4.11
159,Zimbabwe,4.61,4.19,3.88,3.69,3.66

In [8]:
#creating dataframes to each year
Hapiness_2015=pd.DataFrame(Happiness_fouryears[{"Country","2015 Happiness Score"}])
Hapiness_2016=pd.DataFrame(Happiness_fouryears[{"Country","2016 Happiness Score"}])
Hapiness_2017=pd.DataFrame(Happiness_fouryears[{"Country","2017 Happiness Score"}])
Hapiness_2018=pd.DataFrame(Happiness_fouryears[{"Country","2018 Happiness Score"}])
Hapiness_2019=pd.DataFrame(Happiness_fouryears[{"Country","2019 Happiness Score"}])

In [9]:
#add a column with the mean
Happiness_fouryears['Hapiness_Mean'] = Happiness_fouryears.mean(axis=1)

In [10]:
#creating a df with country and mean
Happiness_mean = pd.DataFrame(Happiness_fouryears[{"Country","Hapiness_Mean"}])

Happiness_mean

     Hapiness_Mean               Country
0            3.512           Afghanistan
1            3.860                Angola
2            4.714               Albania
3            6.744  United Arab Emirates
4            6.460             Argentina
..             ...                   ...
155          5.606                Kosovo
156          3.626                 Yemen
157          4.674          South Africa
158          4.586                Zambia
159          4.006              Zimbabwe

[160 rows x 2 columns]

In [11]:
Culture_df = pd.DataFrame(country_happiness[{"Country","Region","Religion","Languages","Christian","Muslim","Irreligion","Hindu","Buddhist",
                                             "Folk religion","Other religion","Jewish"}])

In [12]:
#Dataframe with cultural traits
Culture_df

,Buddhist,Country,Muslim,Other religion,Jewish,Languages,Religion,Region,Irreligion,Christian,Folk religion,Hindu
0,0.00,Afghanistan,99.7,0.06,0.00,Asia (other),Muslim,Southern Asia,0.0,0.1,0.0,0.03
1,0.00,Angola,1.0,0.00,0.00,Portuguese,Christian,Sub-Saharan Africa,5.1,90.5,4.2,0.00
2,0.00,Albania,80.3,0.20,0.00,Europe (other),Muslim,Eastern Europe,1.4,18.0,0.0,0.00
3,2.00,United Arab Emirates,76.9,0.80,0.00,Arabic,Muslim,Middle East and Northern Africa,1.1,12.6,0.0,6.60
4,0.05,Argentina,1.0,0.30,0.50,Spanish,Christian,Latin America and Caribbean,12.2,85.2,0.8,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...
155,0.00,Kosovo,87.0,0.00,0.00,Europe (other),Muslim,Eastern Europe,1.6,11.4,0.0,0.00
156,0.00,Yemen,99.1,0.00,0.00,Arabic,Muslim,Middle East and Northern Africa,0.1,0.2,0.0,0.60
157,0.20,South Africa,2.0,0.30,0.10,English,Christian,Sub-Saharan Africa,14.9,81.2,0.4,1.70
158,0.00,Zambia,1.0,0.90,0.00,English,Christian,Sub-Saharan Africa,0.5,97.6,0.3,0.10
159,0.00,Zimbabwe,1.0,0.30,0.08,English,Christian,Sub-Saharan Africa,7.9,87.0,3.8,0.00

In [13]:
#standardise predominant religion

Culture_df["Religion_Muslim"] = 0
Culture_df.loc[Culture_df.Religion == "Muslim", 'Religion_Muslim'] = 1
Culture_df["Religion_Christian"] = 0
Culture_df.loc[Culture_df.Religion == "Christian", 'Religion_Christian'] = 1
Culture_df["Religion_Buddhist"] = 0
Culture_df.loc[Culture_df.Religion == "Buddhist", 'Religion_Buddhist'] = 1
Culture_df["Religion_Atheist"] = 0
Culture_df.loc[Culture_df.Religion == "Atheist", 'Religion_Atheist'] = 1
Culture_df["Religion_Mixed"] = 0
Culture_df.loc[Culture_df.Religion == "Religion_Mixed", 'Religion_Mixed'] = 1
Culture_df["Religion_Jewish"] = 0
Culture_df.loc[Culture_df.Religion == "Religion_Jewish", 'Religion_Jewish'] = 1
Culture_df["Religion_Folk Religion"] = 0
Culture_df.loc[Culture_df.Religion == "Religion_Folk Religion", "Religion_Folk Religion"] = 1
Culture_df["Religion_Hindu"] = 0
Culture_df.loc[Culture_df.Religion == "Religion_Hindu", 'Religion_Hindu'] = 1

#Standardize Languages
Culture_df["Language_Asia (other)"] = 0
Culture_df.loc[Culture_df.Languages == "Asia (other)", 'Language_Asia (other)'] = 1
Culture_df["Language_Portuguese"] = 0
Culture_df.loc[Culture_df.Languages  == "Portuguese", 'Language_Portuguese'] = 1
Culture_df["Language_Europe (other)"] = 0
Culture_df.loc[Culture_df.Languages  == "Europe (other)", 'Language_Europe (other)'] = 1
Culture_df["Language_Arabic"] = 0
Culture_df.loc[Culture_df.Languages  == "Arabic", 'Language_Arabic'] = 1
Culture_df["Language_Spanish"] = 0
Culture_df.loc[Culture_df.Languages  == "Spanish", 'Language_Spanish'] = 1
Culture_df["Language_English"] = 0
Culture_df.loc[Culture_df.Languages  == "English", 'Language_English'] = 1
Culture_df["Language_German"] = 0
Culture_df.loc[Culture_df.Languages  == "German", 'Language_German'] = 1
Culture_df["Language_French"] = 0
Culture_df.loc[Culture_df.Languages == "French", 'Language_French'] = 1
Culture_df["Language_Chinese"] = 0
Culture_df.loc[Culture_df.Languages == "Chinese", 'Language_Chinese'] = 1
Culture_df["Language_African (other)"] = 0
Culture_df.loc[Culture_df.Languages == "African (other)", 'Language_African (other)'] = 1
Culture_df["Language_Hindi"] = 0
Culture_df.loc[Culture_df.Languages == "Hindi", 'Language_Hindi'] = 1
Culture_df["Language_Persian"] = 0
Culture_df.loc[Culture_df.Languages == "Persian", 'Language_Persian'] = 1
Culture_df["Language_Japanese"] = 0
Culture_df.loc[Culture_df.Languages == "Japanese", 'Language_Japanese'] = 1
Culture_df["Language_Russian"] = 0
Culture_df.loc[Culture_df.Languages == "Russian", 'Language_Russian'] = 1


#Standardise regions
Culture_df["Region_Southern Asia"] = 0
Culture_df.loc[Culture_df.Region == "Southern Asia", 'Region_Southern Asia'] = 1
Culture_df["Region_Sub-Saharan Africa"] = 0
Culture_df.loc[Culture_df.Region == "Sub-Saharan Africa", 'Region_Sub-Saharan Africa'] = 1
Culture_df["Region_Eastern Europe"] = 0
Culture_df.loc[Culture_df.Region == "Eastern Europe", 'Region_Eastern Europe'] = 1
Culture_df["Region_Middle East and Northern Africa"] = 0
Culture_df.loc[Culture_df.Region == "Middle East and Northern Africa", 'Region_Middle East and Northern Africa'] = 1
Culture_df["Region_Latin America and Caribbean"] = 0
Culture_df.loc[Culture_df.Region == "Latin America and Caribbean", 'Region_Latin America and Caribbean'] = 1
Culture_df["Region_Australia and New Zealand"] = 0
Culture_df.loc[Culture_df.Region == "Australia and New Zealand", 'Region_Australia and New Zealand'] = 1
Culture_df["Region_Northern Europe"] = 0
Culture_df.loc[Culture_df.Region == "Northern Europe", 'Region_Northern Europe'] = 1
Culture_df["Region_Southeastern Asia"] = 0
Culture_df.loc[Culture_df.Region == "Southeastern Asia", 'Region_Southeastern Asia'] = 1               
Culture_df["Region_Eastern Asia"] = 0
Culture_df.loc[Culture_df.Region == "Eastern Asia", 'Region_Eastern Asia'] = 1
Culture_df["Region_Southern Europe"] = 0
Culture_df.loc[Culture_df.Region == "Southern Europe", 'Region_Southern Europe'] = 1
Culture_df["Region_Central Asia"] = 0
Culture_df.loc[Culture_df.Region == "Central Asia", 'Region_Central Asia'] = 1



# Southern Asia
# Sub-Saharan Africa
# Eastern Europe
# Middle East and Northern Africa
# Latin America and Caribbean
# Central Asia
# Australia and New Zealand
# Northern Europe
# Southeastern Asia
# Eastern Asia
#Southern Europe




Culture_df

,Buddhist,Country,Muslim,Other religion,Jewish,Languages,Religion,Region,Irreligion,Christian,...,Region_Sub-Saharan Africa,Region_Eastern Europe,Region_Middle East and Northern Africa,Region_Latin America and Caribbean,Region_Australia and New Zealand,Region_Northern Europe,Region_Southeastern Asia,Region_Eastern Asia,Region_Southern Europe,Region_Central Asia
0,0.00,Afghanistan,99.7,0.06,0.00,Asia (other),Muslim,Southern Asia,0.0,0.1,...,0,0,0,0,0,0,0,0,0,0
1,0.00,Angola,1.0,0.00,0.00,Portuguese,Christian,Sub-Saharan Africa,5.1,90.5,...,1,0,0,0,0,0,0,0,0,0
2,0.00,Albania,80.3,0.20,0.00,Europe (other),Muslim,Eastern Europe,1.4,18.0,...,0,1,0,0,0,0,0,0,0,0
3,2.00,United Arab Emirates,76.9,0.80,0.00,Arabic,Muslim,Middle East and Northern Africa,1.1,12.6,...,0,0,1,0,0,0,0,0,0,0
4,0.05,Argentina,1.0,0.30,0.50,Spanish,Christian,Latin America and Caribbean,12.2,85.2,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,0.00,Kosovo,87.0,0.00,0.00,Europe (other),Muslim,Eastern Europe,1.6,11.4,...,0,1,0,0,0,0,0,0,0,0
156,0.00,Yemen,99.1,0.00,0.00,Arabic,Muslim,Middle East and Northern Africa,0.1,0.2,...,0,0,1,0,0,0,0,0,0,0
157,0.20,South Africa,2.0,0.30,0.10,English,Christian,Sub-Saharan Africa,14.9,81.2,...,1,0,0,0,0,0,0,0,0,0
158,0.00,Zambia,1.0,0.90,0.00,English,Christian,Sub-Saharan Africa,0.5,97.6,...,1,0,0,0,0,0,0,0,0,0
159,0.00,Zimbabwe,1.0,0.30,0.08,English,Christian,Sub-Saharan Africa,7.9,87.0,...,1,0,0,0,0,0,0,0,0,0

In [14]:
Cultureadd_df = pd.DataFrame(country_happiness[{"Country","Individualism","Masculinity","Uncertainity Avoidance","Long Term Orientation"}])

#drop countries with null values, only 65 countries to be analysed
Cultureadd_df = Cultureadd_df.dropna()

In [15]:
#check and select columns for economic factors
country_happiness

# iterating the columns 
for col in country_happiness.columns: 
    print(col) # iterating the columns

Overall rank
Country Code
Country
Region
Languages
Religion
Population
Area (km2)
2015 Happiness Score
2016 Happiness Score
2017 Happiness Score
2018 Happiness Score
2019 Happiness Score
2015 GDP
2016 GDP
2017 GDP
2018 GDP
2019 GDP
2015 Family
2016 Family
2017 Family
2018 Family
2019 Family
2015 Health
2016 Health
2017 Health
2018 Health
2019 Health
2015 Freedom
2016 Freedom
2017 Freedom
2018 Freedom
2019 Freedom
2015 Corruption
2016 Corruption
2017 Corruption
2018 Corruption
2019 Corruption
2015 Generosity
2016 Generosity
2017 Generosity
2018 Generosity
2019 Generosity
2015 GDP per Cap
2016 GDP per Cap
2017 GDP per Cap
2018 GDP per Cap
2019 GDP per Cap
Gender Ratio %
Gender Gap
2015 Suicide per 100k
2016 Suicide per 100k
2015 Suicide 5-14 years
2016 Suicide 5-14 years
2015Suicide 15-49 years
2016 Suicide 15-49 years
2015 Suicide  50-69 years
2016 Suicide  50-69 years
2015 Suicide 70+ years
2016 Suicide 70+ years
Unemployment (%)
Divorce Rate per 100k
GINI
Christian
Muslim
Irreligion
Hindu
Buddhist
Folk religion
Other religion
Jewish
Hunger (rate)
Urbanization (rate)
Democracy (value)
Holiday (Paid Days)
Fertility (per woman)
Air Quality (Value)
Homicide per 100k
Prison (per 100k)
Alchool (per cap)
Drugs Usage (per cap)
Antidepressants (per cap)
Congestion (Per capita)
Power Distance
Individualism
Masculinity
Uncertainity Avoidance
Long Term Orientation
Net Migration
Mortality

In [16]:
Economic_df = pd.DataFrame(country_happiness[{"Country","2015 GDP per Cap","2016 GDP per Cap","2017 GDP per Cap","2018 GDP per Cap",
                                              "2019 GDP per Cap","GINI","Hunger (rate)",
                                              "Urbanization (rate)","Air Quality (Value)","Congestion (Per capita)",
                                              "Net Migration","Unemployment (%)"}])

Economic_df

,Urbanization (rate),2018 GDP per Cap,2016 GDP per Cap,2015 GDP per Cap,Country,GINI,Air Quality (Value),Congestion (Per capita),2017 GDP per Cap,Unemployment (%),Hunger (rate),Net Migration,2019 GDP per Cap
0,26.0,524.16,547.23,578.47,Afghanistan,NaN,58.80,NaN,556.30,8.86,33.8,3.3,502.12
1,66.8,3289.65,3506.07,4166.98,Angola,51.3,15.90,NaN,4095.81,7.28,29.8,1.4,2973.59
2,62.1,5284.38,4124.06,3952.80,Albania,33.2,NaN,NaN,4531.02,17.08,7.0,-9.4,5352.86
3,87.0,43839.36,38141.85,38663.38,United Arab Emirates,32.5,38.94,170.89,40644.80,1.93,NaN,6.1,43103.32
4,92.1,11683.95,12790.24,13789.06,Argentina,41.4,14.60,172.79,14591.86,7.15,5.0,0.1,10006.15
...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,NaN,4419.91,3780.00,3603.03,Kosovo,29.0,23.50,NaN,4045.61,NaN,NaN,NaN,4417.51
156,36.6,968.16,1033.73,1395.44,Yemen,36.7,NaN,NaN,882.40,13.81,45.9,-0.6,0.00
157,67.4,6374.03,5272.92,5734.63,South Africa,63.0,21.56,191.72,6132.48,25.16,14.0,3.5,6001.40
158,44.6,1556.33,1280.58,1337.80,Zambia,57.1,NaN,NaN,1534.87,7.75,38.1,-0.7,1291.34
159,32.2,1683.74,1464.58,1445.07,Zimbabwe,44.3,NaN,NaN,1548.17,5.09,34.4,-9.4,1463.99

In [17]:
Economic_df['GDP_Mean'] = Economic_df[{"2015 GDP per Cap","2016 GDP per Cap","2017 GDP per Cap","2018 GDP per Cap",
                                              "2019 GDP per Cap"}].mean(axis=1)

Economic_df

,Urbanization (rate),2018 GDP per Cap,2016 GDP per Cap,2015 GDP per Cap,Country,GINI,Air Quality (Value),Congestion (Per capita),2017 GDP per Cap,Unemployment (%),Hunger (rate),Net Migration,2019 GDP per Cap,GDP_Mean
0,26.0,524.16,547.23,578.47,Afghanistan,NaN,58.80,NaN,556.30,8.86,33.8,3.3,502.12,541.656
1,66.8,3289.65,3506.07,4166.98,Angola,51.3,15.90,NaN,4095.81,7.28,29.8,1.4,2973.59,3606.420
2,62.1,5284.38,4124.06,3952.80,Albania,33.2,NaN,NaN,4531.02,17.08,7.0,-9.4,5352.86,4649.024
3,87.0,43839.36,38141.85,38663.38,United Arab Emirates,32.5,38.94,170.89,40644.80,1.93,NaN,6.1,43103.32,40878.542
4,92.1,11683.95,12790.24,13789.06,Argentina,41.4,14.60,172.79,14591.86,7.15,5.0,0.1,10006.15,12572.252
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,NaN,4419.91,3780.00,3603.03,Kosovo,29.0,23.50,NaN,4045.61,NaN,NaN,NaN,4417.51,4053.212
156,36.6,968.16,1033.73,1395.44,Yemen,36.7,NaN,NaN,882.40,13.81,45.9,-0.6,0.00,855.946
157,67.4,6374.03,5272.92,5734.63,South Africa,63.0,21.56,191.72,6132.48,25.16,14.0,3.5,6001.40,5903.092
158,44.6,1556.33,1280.58,1337.80,Zambia,57.1,NaN,NaN,1534.87,7.75,38.1,-0.7,1291.34,1400.184
159,32.2,1683.74,1464.58,1445.07,Zimbabwe,44.3,NaN,NaN,1548.17,5.09,34.4,-9.4,1463.99,1521.110

In [18]:
Incomplete_Countries = Economic_df[Economic_df.isna().any(axis=1)]


Incomplete_Countries

,Urbanization (rate),2018 GDP per Cap,2016 GDP per Cap,2015 GDP per Cap,Country,GINI,Air Quality (Value),Congestion (Per capita),2017 GDP per Cap,Unemployment (%),Hunger (rate),Net Migration,2019 GDP per Cap,GDP_Mean
0,26.0,524.16,547.23,578.47,Afghanistan,NaN,58.80,NaN,556.30,8.86,33.8,3.3,502.12,541.656
1,66.8,3289.65,3506.07,4166.98,Angola,51.3,15.90,NaN,4095.81,7.28,29.8,1.4,2973.59,3606.420
2,62.1,5284.38,4124.06,3952.80,Albania,33.2,NaN,NaN,4531.02,17.08,7.0,-9.4,5352.86,4649.024
3,87.0,43839.36,38141.85,38663.38,United Arab Emirates,32.5,38.94,170.89,40644.80,1.93,NaN,6.1,43103.32,40878.542
5,63.3,4220.49,3591.83,3607.30,Armenia,34.4,25.51,NaN,3914.50,18.26,7.8,-2.1,4622.73,3991.370
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
153,88.3,0.00,0.00,0.00,Venezuela,46.9,NaN,155.42,0.00,6.82,16.9,-2.9,0.00,0.000
155,NaN,4419.91,3780.00,3603.03,Kosovo,29.0,23.50,NaN,4045.61,NaN,NaN,NaN,4417.51,4053.212
156,36.6,968.16,1033.73,1395.44,Yemen,36.7,NaN,NaN,882.40,13.81,45.9,-0.6,0.00,855.946
158,44.6,1556.33,1280.58,1337.80,Zambia,57.1,NaN,NaN,1534.87,7.75,38.1,-0.7,1291.34,1400.184
159,32.2,1683.74,1464.58,1445.07,Zimbabwe,44.3,NaN,NaN,1548.17,5.09,34.4,-9.4,1463.99,1521.110

In [19]:
#should we drop some columns and get more data?
Incomplete_Countries.isnull().sum(axis = 0)

Urbanization (rate)         4
2018 GDP per Cap            0
2016 GDP per Cap            0
2015 GDP per Cap            0
Country                     0
GINI                       12
Air Quality (Value)        66
Congestion (Per capita)    77
2017 GDP per Cap            0
Unemployment (%)            2
Hunger (rate)              51
Net Migration               5
2019 GDP per Cap            0
GDP_Mean                    0
dtype: int64

In [20]:
#Not bad to drop all columns because we will be comparing the worst economically, exactly what we think it's a differentiator
Economic_df = Economic_df.dropna()

In [21]:
Social_df = pd.DataFrame(country_happiness[{"Country","Gender Ratio %","Democracy (value)",
                                              "Holiday (Paid Days)","Prison (per 100k)","Alchool (per cap)",
                                              "Alchool (per cap)","Homicide per 100k","Fertility (per woman)"}])

In [22]:
Incomplete_Social = Social_df[Social_df.isna().any(axis=1)]
Incomplete_Social.isnull().sum(axis = 0)

Prison (per 100k)        1
Country                  0
Fertility (per woman)    0
Homicide per 100k        0
Democracy (value)        5
Alchool (per cap)        0
Gender Ratio %           0
Holiday (Paid Days)      2
dtype: int64

In [23]:
# Decided to drop gender gap and divorce as they lack substantial data
Social_df = Social_df.dropna()
Social_df

,Prison (per 100k),Country,Fertility (per woman),Homicide per 100k,Democracy (value),Alchool (per cap),Gender Ratio %,Holiday (Paid Days)
0,87.0,Afghanistan,4.98,6.66,2.85,0.2,48.61,35.0
1,93.0,Angola,5.77,4.85,3.72,6.4,50.54,33.0
2,177.0,Albania,1.68,2.29,5.89,7.5,49.09,32.0
3,104.0,United Arab Emirates,1.54,0.50,2.76,3.8,29.60,32.0
4,230.0,Argentina,2.30,5.32,7.02,9.8,51.27,25.0
...,...,...,...,...,...,...,...,...
154,128.0,Vietnam,2.01,1.52,3.08,8.4,50.15,22.0
156,53.0,Yemen,4.10,6.66,1.95,0.1,49.60,37.0
157,275.0,South Africa,2.48,36.40,7.24,9.3,50.64,27.0
158,123.0,Zambia,4.92,5.30,5.09,4.8,50.52,31.0
159,114.0,Zimbabwe,3.90,6.67,3.16,4.8,52.45,33.0

In [24]:
# Country breakdown (developed is to distinguish the very wealthy)

Developed_countries = ["Luxembourg","Switzerland","Ireland","Norway","Iceland","Singapore","United States","Qatar","Denmark",
                       "Australia","Netherlands","Sweden","Austria","Hong Kong","Finland","Germany","Canada","Belgium","Israel",
                       "United Arab Emirates","United Kingdom","New Zealand","France","Japan","Italy","Kuwait","South Korea","Spain"] 

Developing_countries = ["Iran","Kosovo","Slovenia","Cyprus","Estonia","Montenegro","Belarus","Czech Republic","Lithuania","Hungary",
                        "Portugal","Latvia","Greece","Poland","Croatia","Serbia","Slovakia","Russia","Bosnia and Herzegovina",
                        "North Macedonia","Bulgaria","Saudi Arabia","Romania","Bahrain","Chile","Malta","Uruguay","Sri Lanka",
                        "Lebanon","China","Ukraine","Malaysia","Costa Rica","Thailand","Argentina","Georgia","Turkey","Albania",
                        "Kazakhstan","Libya","Peru","Armenia","El Salvador","Colombia","Jamaica","Ecuador","Mexico","Brazil","Moldova",
                        "Panama","Jordan","Mongolia","Mauritius","Nicaragua","Tunisia","Honduras","Uzbekistan","Trinidad and Tobago",
                        "Vietnam","Kyrgyzstan","Paraguay","Egypt","Azerbaijan","Morocco","Algeria","Indonesia","Guatemala","Venezuela",
                        "Bolivia","Philippines","Iraq","Cambodia","Dominican Republic","Bhutan","Bangladesh","South Africa","India"]


Underdeveloped_countries = ["Botswana","Gabon","Turkmenistan","Namibia","Swaziland","Laos","Ivory Coast","Nigeria","Ghana",
                            "Congo (Brazzaville)","Kenya","Mauritania","Cameroon","Zimbabwe","Senegal","Myanmar","Comoros",
                            "Zambia","Pakistan","Benin","Lesotho","Tanzania","South Sudan","Nepal","Yemen","Guinea","Mali",
                            "Tajikistan","Ethiopia","Rwanda","Uganda","Burkina Faso","Haiti","Gambia","Chad","Togo","Liberia",
                            "Niger","Congo (Kinshasa)","Madagascar","Sierra Leone","Afghanistan","Mozambique",
                            "Central African Republic","Malawi","Somalia","Burundi","Syria"]

In [25]:
#breakdown for happiness
Happiness_developed = Happiness_fouryears[Happiness_fouryears['Country'].isin(Developed_countries)]
Happiness_developing = Happiness_fouryears[Happiness_fouryears['Country'].isin(Developing_countries)]
Happiness_underdeveloped = Happiness_fouryears[Happiness_fouryears['Country'].isin(Underdeveloped_countries)]

#breakdown for happiness means
Happiness_mean_developed = Happiness_mean[Happiness_mean['Country'].isin(Developed_countries)]
Happiness_mean_developing = Happiness_mean[Happiness_mean['Country'].isin(Developing_countries)]
Happiness_mean_underdeveloped = Happiness_mean[Happiness_mean['Country'].isin(Underdeveloped_countries)]


#breakdown for culture
Culture_developed = Culture_df[Culture_df['Country'].isin(Developed_countries)]
Culture_developing = Culture_df[Culture_df['Country'].isin(Developing_countries)]
Culture_underdeveloped = Culture_df[Culture_df['Country'].isin(Underdeveloped_countries)]


#breakdown for aditional culture
Behaviour_developed = Cultureadd_df[Cultureadd_df['Country'].isin(Developed_countries)]
Behaviour_developing = Cultureadd_df[Cultureadd_df['Country'].isin(Developing_countries)]
Behaviour_underdeveloped = Cultureadd_df[Cultureadd_df['Country'].isin(Underdeveloped_countries)]

#breakdown for economic
Economic_developed = Economic_df[Economic_df['Country'].isin(Developed_countries)] #should not have data for wealthy countries!
Economic_developing = Economic_df[Economic_df['Country'].isin(Developing_countries)]
Economic_underdeveloped = Economic_df[Economic_df['Country'].isin(Underdeveloped_countries)]

#breakdown for social
Social_developed = Social_df[Social_df['Country'].isin(Developed_countries)]
Social_developing = Social_df[Social_df['Country'].isin(Developing_countries)]
Social_underdeveloped = Social_df[Social_df['Country'].isin(Underdeveloped_countries)]

Culture_underdeveloped

,Buddhist,Country,Muslim,Other religion,Jewish,Languages,Religion,Region,Irreligion,Christian,...,Region_Sub-Saharan Africa,Region_Eastern Europe,Region_Middle East and Northern Africa,Region_Latin America and Caribbean,Region_Australia and New Zealand,Region_Northern Europe,Region_Southeastern Asia,Region_Eastern Asia,Region_Southern Europe,Region_Central Asia
0,0.00,Afghanistan,99.7,0.06,0.00,Asia (other),Muslim,Southern Asia,0.00,0.10,...,0,0,0,0,0,0,0,0,0,0
9,0.00,Burundi,10.0,0.00,0.00,French,Christian,Sub-Saharan Africa,0.00,91.50,...,1,0,0,0,0,0,0,0,0,0
11,0.00,Benin,28.0,0.00,0.00,French,Christian,Sub-Saharan Africa,6.00,48.00,...,1,0,0,0,0,0,0,0,0,0
12,0.00,Burkina Faso,62.0,0.00,0.00,French,Muslim,Sub-Saharan Africa,0.40,22.50,...,1,0,0,0,0,0,0,0,0,0
22,0.00,Botswana,0.4,0.60,0.00,English,Christian,Sub-Saharan Africa,20.60,72.10,...,1,0,0,0,0,0,0,0,0,0
23,0.00,Central African Republic,15.0,0.00,0.00,French,Christian,Sub-Saharan Africa,1.00,89.50,...,1,0,0,0,0,0,0,0,0,0
28,0.00,Ivory Coast,43.2,0.20,0.00,French,Mixed,Sub-Saharan Africa,8.00,44.10,...,1,0,0,0,0,0,0,0,0,0
29,0.00,Cameroon,30.0,2.70,0.00,French,Christian,Sub-Saharan Africa,5.30,70.30,...,1,0,0,0,0,0,0,0,0,0
30,0.00,Congo (Kinshasa),15.0,0.10,0.00,French,Christian,Sub-Saharan Africa,1.80,95.80,...,1,0,0,0,0,0,0,0,0,0
31,0.00,Congo (Brazzaville),2.0,1.10,0.00,French,Christian,Sub-Saharan Africa,9.00,85.90,...,1,0,0,0,0,0,0,0,0,0
33,0.00,Comoros,99.8,0.00,0.00,French,Muslim,Sub-Saharan Africa,0.00,0.20,...,1,0,0,0,0,0,0,0,0,0
46,0.00,Ethiopia,42.6,0.00,1.00,African (other),Mixed,Sub-Saharan Africa,0.06,54.00,...,1,0,0,0,0,0,0,0,0,0
49,0.00,Gabon,11.2,0.70,0.00,French,Christian,Sub-Saharan Africa,5.60,76.50,...,1,0,0,0,0,0,0,0,0,0
52,0.00,Ghana,17.8,0.20,0.00,English,Christian,Sub-Saharan Africa,4.20,74.90,...,1,0,0,0,0,0,0,0,0,0
53,0.00,Guinea,84.4,0.00,0.00,French,Muslim,Sub-Saharan Africa,1.80,10.90,...,1,0,0,0,0,0,0,0,0,0
54,0.00,Gambia,95.1,0.00,0.00,French,Muslim,Sub-Saharan Africa,0.00,4.50,...,1,0,0,0,0,0,0,0,0,0
60,0.00,Haiti,0.1,0.30,0.00,French,Christian,Latin America and Caribbean,10.60,86.90,...,0,0,0,1,0,0,0,0,0,0
74,0.00,Kenya,9.7,1.20,0.00,English,Christian,Sub-Saharan Africa,2.50,84.80,...,1,0,0,0,0,0,0,0,0,0
79,66.00,Laos,0.0,0.70,0.00,Asia (other),Buddhist,Southeastern Asia,0.90,1.50,...,0,0,0,0,0,0,1,0,0,0
81,0.00,Liberia,20.0,0.10,0.00,English,Christian,Sub-Saharan Africa,1.40,85.90,...,1,0,0,0,0,0,0,0,0,0
84,0.00,Lesotho,0.1,0.00,0.00,English,Christian,Sub-Saharan Africa,3.10,96.70,...,1,0,0,0,0,0,0,0,0,0
90,0.00,Madagascar,3.0,0.10,0.00,French,Christian,Sub-Saharan Africa,6.90,85.30,...,1,0,0,0,0,0,0,0,0,0
93,0.00,Mali,95.0,0.00,0.00,French,Muslim,Sub-Saharan Africa,0.60,3.20,...,1,0,0,0,0,0,0,0,0,0
95,80.10,Myanmar,4.0,0.20,0.00,Asia (other),Buddhist,Southeastern Asia,0.50,7.80,...,0,0,0,0,0,0,1,0,0,0
98,0.00,Mozambique,18.0,0.00,0.00,Portuguese,Christian,Sub-Saharan Africa,17.90,56.70,...,1,0,0,0,0,0,0,0,0,0
99,0.00,Mauritania,99.9,0.00,0.00,French,Muslim,Sub-Saharan Africa,0.00,0.10,...,1,0,0,0,0,0,0,0,0,0
101,0.00,Malawi,13.0,0.00,0.00,French,Christian,Sub-Saharan Africa,2.50,82.70,...,1,0,0,0,0,0,0,0,0,0
103,0.00,Namibia,0.3,0.00,0.00,English,Christian,Sub-Saharan Africa,1.90,97.50,...,1,0,0,0,0,0,0,0,0,0
104,0.00,Niger,98.4,0.00,0.00,French,Muslim,Sub-Saharan Africa,0.70,0.80,...,1,0,0,0,0,0,0,0,0,0
105,0.01,Nigeria,51.0,0.06,0.00,English,Mixed,Sub-Saharan Africa,0.04,48.00,...,1,0,0,0,0,0,0,0,0,0
109,10.30,Nepal,4.6,0.07,0.00,Asia (other),Hindu,Southern Asia,0.30,0.50,...,0,0,0,0,0,0,0,0,0,0
112,0.01,Pakistan,96.4,0.01,0.00,Asia (other),Muslim,Southern Asia,0.01,1.60,...,0,0,0,0,0,0,0,0,0,0
123,0.00,Rwanda,4.8,0.20,0.00,English,Christian,Sub-Saharan Africa,3.60,93.40,...,1,0,0,0,0,0,0,0,0,0
126,0.00,Senegal,92.0,0.00,0.00,French,Muslim,Sub-Saharan Africa,0.20,5.00,...,1,0,0,0,0,0,0,0,0,0
128,0.00,Sierra Leone,78.0,0.00,0.00,English,Muslim,Sub-Saharan Africa,0.10,21.00,...,1,0,0,0,0,0,0,0,0,0
130,0.00,Somalia,99.8,0.00,0.00,Arabic,Muslim,Sub-Saharan Africa,0.00,0.01,...,1,0,0,0,0,0,0,0,0,0
132,0.00,South Sudan,20.0,0.00,0.00,English,Christian,Sub-Saharan Africa,0.50,60.50,...,1,0,0,0,0,0,0,0,0,0
137,0.00,Swaziland,2.0,0.40,0.00,English,Christian,Sub-Saharan Africa,10.10,88.10,...,1,0,0,0,0,0,0,0,0,0
138,0.00,Syria,92.8,0.00,0.00,Arabic,Muslim,Middle East and Northern Africa,2.00,5.20,...,0,0,1,0,0,0,0,0,0,0
139,0.00,Chad,58.0,0.10,0.00,French,Mixed,Sub-Saharan Africa,2.50,40.60,...,1,0,0,0,0,0,0,0,0,0
140,0.00,Togo,20.0,0.60,0.00,French,Muslim,Sub-Saharan Africa,6.20,43.70,...,1,0,0,0,0,0,0,0,0,0
142,0.00,Tajikistan,96.7,0.00,0.00,Asia (other),Muslim,Central Asia,1.50,1.60,...,0,0,0,0,0,0,0,0,0,1
143,0.00,Turkmenistan,93.0,0.00,0.00,Asia (other),Muslim,Central Asia,0.50,6.40,...,0,0,0,0,0,0,0,0,0,1
147,0.00,Tanzania,35.2,0.07,0.00,English,Mixed,Sub-Saharan Africa,1.40,61.40,...,1,0,0,0,0,0,0,0,0,0
148,0.00,Uganda,11.5,0.10,0.00,English,Christian,Sub-Saharan Africa,0.50,86.70,...,1,0,0,0,0,0,0,0,0,0
156,0.00,Yemen,99.1,0.00,0.00,Arabic,Muslim,Middle East and Northern Africa,0.10,0.20,...,0,0,1,0,0,0,0,0,0,0
158,0.00,Zambia,1.0,0.90,0.00,English,Christian,Sub-Saharan Africa,0.50,97.60,...,1,0,0,0,0,0,0,0,0,0
159,0.00,Zimbabwe,1.0,0.30,0.08,English,Christian,Sub-Saharan Africa,7.90,87.00,...,1,0,0,0,0,0,0,0,0,0

In [26]:
#Developing happiness frames for each section
Happiness_mean_Culture_developed = Happiness_mean_developed[Happiness_developed["Country"].isin(Culture_developed["Country"])]
Happiness_mean_Culture_developing = Happiness_mean_developing[Happiness_mean_developing["Country"].isin(Culture_developing["Country"])]
Happiness_mean_Culture_underdeveloped = Happiness_mean_underdeveloped[Happiness_mean_underdeveloped["Country"].isin(Culture_underdeveloped["Country"])]

Happiness_mean_Behaviour_developed = Happiness_mean_developed[Happiness_developed["Country"].isin(Behaviour_developed["Country"])]
Happiness_mean_Behaviour_developing = Happiness_mean_developing[Happiness_mean_developing["Country"].isin(Behaviour_developing["Country"])]
Happiness_mean_Behaviour_underdeveloped = Happiness_mean_underdeveloped[Happiness_mean_underdeveloped["Country"].isin(Behaviour_underdeveloped["Country"])]

Happiness_mean_Economic_developed = Happiness_mean_developed[Happiness_developed["Country"].isin(Economic_developed["Country"])]
Happiness_mean_Economic_developing = Happiness_mean_developing[Happiness_mean_developing["Country"].isin(Economic_developing["Country"])]
Happiness_mean_Economic_underdeveloped = Happiness_mean_underdeveloped[Happiness_mean_underdeveloped["Country"].isin(Economic_underdeveloped["Country"])]

Happiness_mean_Social_developed = Happiness_mean_developed[Happiness_developed["Country"].isin(Social_developed["Country"])]
Happiness_mean_Social_developing = Happiness_mean_developing[Happiness_mean_developing["Country"].isin(Social_developing["Country"])]
Happiness_mean_Social_underdeveloped = Happiness_mean_underdeveloped[Happiness_mean_underdeveloped["Country"].isin(Social_underdeveloped["Country"])]

In [27]:
#time to drop columns this is fun!

#trim culture
Happiness_Culture_developed_trim = Happiness_mean_Culture_developed.drop("Country", 1)
Happiness_Culture_developing_trim = Happiness_mean_Culture_developing.drop("Country", 1)
Happiness_Culture_underdeveloped_trim = Happiness_mean_Culture_underdeveloped.drop("Country", 1)

Culture_developed_trim = Culture_developed.drop({"Country","Languages","Region","Religion"}, 1)
Culture_developing_trim = Culture_developing.drop({"Country","Languages","Region","Religion"}, 1)
Culture_underdeveloped_trim = Culture_underdeveloped.drop({"Country","Languages","Region","Religion"}, 1)

In [28]:
# Normalise
normed_Happiness_Culture_developed_trim = (Happiness_Culture_developed_trim - Happiness_Culture_developed_trim.min()) / (
    Happiness_Culture_developed_trim.max() - Happiness_Culture_developed_trim.min())

normed_Happiness_Culture_developing_trim = (Happiness_Culture_developing_trim - Happiness_Culture_developing_trim.min()) / (
    Happiness_Culture_developing_trim.max() - Happiness_Culture_developing_trim.min())

normed_Happiness_Culture_underdeveloped_trim = (Happiness_Culture_underdeveloped_trim - Happiness_Culture_underdeveloped_trim.min()) / (
    Happiness_Culture_underdeveloped_trim.max() - Happiness_Culture_underdeveloped_trim.min())

In [29]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler() 
Culture_developed_scaled = scaler.fit_transform(Culture_developed_trim) 
Culture_developed_scaled = pd.DataFrame(Culture_developed_scaled, columns=Culture_developed_trim.columns,index=Culture_developed_trim.index)

Culture_developing_scaled = scaler.fit_transform(Culture_developing_trim) 
Culture_developing_scaled = pd.DataFrame(Culture_developing_scaled, columns=Culture_developing_trim.columns,index=Culture_developing_trim.index)

Culture_underdeveloped_scaled = scaler.fit_transform(Culture_underdeveloped_trim) 
Culture_underdeveloped_scaled = pd.DataFrame(Culture_underdeveloped_scaled, columns=Culture_underdeveloped_trim.columns,index=Culture_underdeveloped_trim.index)

In [30]:
normed_Happiness_Culture_underdeveloped_trim

     Hapiness_Mean
0         0.171863
9         0.000000
11        0.326938
12        0.396483
22        0.298961
23        0.031575
28        0.476419
29        0.645084
30        0.505995
31        0.517986
33        0.351719
46        0.536371
49        0.530775
52        0.581934
53        0.308553
54        0.574740
60        0.313349
74        0.546763
79        0.681055
81        0.302958
84        0.420863
90        0.264588
93        0.454836
95        0.521183
98        0.620304
99        0.509193
101       0.320544
103       0.589928
104       0.410072
105       0.818545
109       0.690647
112       0.903277
123       0.143086
126       0.523581
128       0.590727
130       0.844125
132       0.178257
137       0.556355
138       0.083933
139       0.368505
140       0.184652
142       0.806555
143       1.000000
147       0.153477
148       0.374900
156       0.217426
158       0.601119
159       0.369305

In [31]:
Culture_underdeveloped_scaled

,Buddhist,Muslim,Other religion,Jewish,Irreligion,Christian,Folk religion,Hindu,Religion_Muslim,Religion_Christian,...,Region_Sub-Saharan Africa,Region_Eastern Europe,Region_Middle East and Northern Africa,Region_Latin America and Caribbean,Region_Australia and New Zealand,Region_Northern Europe,Region_Southeastern Asia,Region_Eastern Asia,Region_Southern Europe,Region_Central Asia
0,0.000000,0.997998,0.022222,0.00,0.000000,0.000922,0.000000,0.000372,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0.000000,0.100100,0.000000,0.00,0.000000,0.937494,0.160112,0.000000,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,0.000000,0.280280,0.000000,0.00,0.291262,0.491751,0.505618,0.000000,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,0.000000,0.620621,0.000000,0.00,0.019417,0.230454,0.432584,0.000000,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,0.000000,0.004004,0.222222,0.00,1.000000,0.738703,0.168539,0.003717,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,0.000000,0.150150,0.000000,0.00,0.048544,0.917000,0.028090,0.000000,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,0.000000,0.432432,0.074074,0.00,0.388350,0.451788,0.286517,0.000000,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,0.000000,0.300300,1.000000,0.00,0.257282,0.720258,0.092697,0.000000,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30,0.000000,0.150150,0.037037,0.00,0.087379,0.981555,0.019663,0.000620,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31,0.000000,0.020020,0.407407,0.00,0.436893,0.880111,0.078652,0.000000,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
33,0.000000,0.998999,0.000000,0.00,0.000000,0.001947,0.000000,0.000000,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
46,0.000000,0.426426,0.000000,1.00,0.002913,0.553233,0.073034,0.000000,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49,0.000000,0.112112,0.259259,0.00,0.271845,0.783789,0.168539,0.000000,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
52,0.000000,0.178178,0.074074,0.00,0.203883,0.767394,0.137640,0.000000,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
53,0.000000,0.844845,0.000000,0.00,0.087379,0.111589,0.075843,0.000000,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
54,0.000000,0.951952,0.000000,0.00,0.000000,0.046009,0.002809,0.000000,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
60,0.000000,0.001001,0.111111,0.00,0.514563,0.890358,0.061798,0.000000,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
74,0.000000,0.097097,0.444444,0.00,0.121359,0.868839,0.047753,0.001239,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
79,0.823970,0.000000,0.259259,0.00,0.043689,0.015268,0.862360,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
81,0.000000,0.200200,0.037037,0.00,0.067961,0.880111,0.014045,0.000000,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
84,0.000000,0.001001,0.000000,0.00,0.150485,0.990778,0.002809,0.000000,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
90,0.000000,0.030030,0.037037,0.00,0.334951,0.873962,0.126404,0.000620,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
93,0.000000,0.950951,0.000000,0.00,0.029126,0.032688,0.033708,0.000000,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
95,1.000000,0.040040,0.074074,0.00,0.024272,0.079824,0.162921,0.021066,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
98,0.000000,0.180180,0.000000,0.00,0.868932,0.580900,0.207865,0.000000,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
99,0.000000,1.000000,0.000000,0.00,0.000000,0.000922,0.000000,0.000000,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
101,0.000000,0.130130,0.000000,0.00,0.121359,0.847320,0.047753,0.000000,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
103,0.000000,0.003003,0.000000,0.00,0.092233,0.998975,0.005618,0.000000,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
104,0.000000,0.984985,0.000000,0.00,0.033981,0.008095,0.000000,0.000000,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
105,0.000125,0.510511,0.022222,0.00,0.001942,0.491751,0.028090,0.000000,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
109,0.128589,0.046046,0.025926,0.00,0.014563,0.005021,0.103933,1.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
112,0.000125,0.964965,0.003704,0.00,0.000485,0.016293,0.000562,0.023544,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
123,0.000000,0.048048,0.074074,0.00,0.174757,0.956963,0.028090,0.000000,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
126,0.000000,0.920921,0.000000,0.00,0.009709,0.051132,0.078652,0.000000,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
128,0.000000,0.780781,0.000000,0.00,0.004854,0.215084,0.028090,0.000000,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
130,0.000000,0.998999,0.000000,0.00,0.000000,0.000000,0.000000,0.000000,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
132,0.000000,0.200200,0.000000,0.00,0.024272,0.619838,0.924157,0.000000,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
137,0.000000,0.020020,0.148148,0.00,0.490291,0.902654,0.028090,0.001239,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
138,0.000000,0.928929,0.000000,0.00,0.097087,0.053182,0.000000,0.000000,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
139,0.000000,0.580581,0.037037,0.00,0.121359,0.415924,0.039326,0.000000,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
140,0.000000,0.200200,0.222222,0.00,0.300971,0.447689,1.000000,0.000000,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
142,0.000000,0.967968,0.000000,0.00,0.072816,0.016293,0.000000,0.000000,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
143,0.000000,0.930931,0.000000,0.00,0.024272,0.065478,0.000000,0.000000,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
147,0.000000,0.352352,0.025926,0.00,0.067961,0.629060,0.050562,0.001239,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
148,0.000000,0.115115,0.037037,0.00,0.024272,0.888308,0.025281,0.003717,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
156,0.000000,0.991992,0.000000,0.00,0.004854,0.001947,0.000000,0.007435,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
158,0.000000,0.010010,0.333333,0.00,0.024272,1.000000,0.008427,0.001239,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
159,0.000000,0.010010,0.111111,0.08,0.383495,0.891382,0.106742,0.000000,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [33]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(n_estimators=200)
rf = rf.fit(Culture_developing_scaled, normed_Happiness_Culture_developing_trim)
rf.score(Culture_developing_scaled, normed_Happiness_Culture_developing_trim)

importances = rf.feature_importances_
importances

sorted(zip(rf.feature_importances_, Culture_developing_scaled), reverse=True)

C:\Users\Luis Nunes\anaconda3\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.

[(0.2031584401493161, 'Muslim'),
 (0.17431504379746712, 'Irreligion'),
 (0.1548467455205111, 'Region_Latin America and Caribbean'),
 (0.1301873530305791, 'Christian'),
 (0.06144443755592732, 'Jewish'),
 (0.05316088082171392, 'Folk religion'),
 (0.05041201113460007, 'Buddhist'),
 (0.040039401425744414, 'Other religion'),
 (0.034427902203061966, 'Hindu'),
 (0.01646597649531021, 'Region_Central Asia'),
 (0.011378822505748615, 'Region_Southern Asia'),
 (0.009168923703598054, 'Language_Spanish'),
 (0.009055983368478716, 'Language_Russian'),
 (0.007196322088274788, 'Language_Europe (other)'),
 (0.006104764060285654, 'Region_Eastern Europe'),
 (0.005977453659541916, 'Religion_Atheist'),
 (0.004294760659860949, 'Language_English'),
 (0.004081482116608958, 'Language_Asia (other)'),
 (0.0032912555859179377, 'Region_Middle East and Northern Africa'),
 (0.0032456335670545755, 'Religion_Christian'),
 (0.003070737765156212, 'Region_Southern Europe'),
 (0.0030234027430668946, 'Language_Arabic'),
 (0.002799137317006027, 'Religion_Buddhist'),
 (0.002690284568368199, 'Region_Southeastern Asia'),
 (0.0015311774059215578, 'Religion_Muslim'),
 (0.0011580014756832997, 'Region_Northern Europe'),
 (0.0011161423528894307, 'Region_Sub-Saharan Africa'),
 (0.0006772247863056414, 'Language_Persian'),
 (0.0005109263923508695, 'Language_French'),
 (0.0005037663265284978, 'Language_Portuguese'),
 (0.00032380741520919294, 'Language_Hindi'),
 (0.0002917825083198168, 'Region_Eastern Asia'),
 (5.00154935930135e-05, 'Language_Chinese'),
 (0.0, 'Religion_Mixed'),
 (0.0, 'Religion_Jewish'),
 (0.0, 'Religion_Hindu'),
 (0.0, 'Religion_Folk Religion'),
 (0.0, 'Region_Australia and New Zealand'),
 (0.0, 'Language_Japanese'),
 (0.0, 'Language_German'),
 (0.0, 'Language_African (other)')]